### ISSUE TITLE
Black / White Logo

### ISSUE THREAD

**Issue by stefenfriesen** [jekyll/brand#12]
I was adding the Jekyll logo to my website footer to promote it and realized there aren't any single colour logos available. A lot of people prefer a solid black or white logo to match the aesthetic of their websites. I modified the SVG for my use, but I'm wondering if a) this violates any usage guidelines, and b) would you like me to provide the SVG?

![jekyll](https://cloud.githubusercontent.com/assets/6977140/5790861/bbfbf980-9e62-11e4-894a-b2ab08ed203f.png)

Also, please bear with me. I'm new to GitHub and not sure if this should be an issue or pull request.

**Comment by parkr** [comment]
Hey @stefenfriesen!

> I'm wondering if a) this violates any usage guidelines

Our license is MIT, so you can basically do anything with it. :)

> b) would you like me to provide the SVG?

That would be terrific! I think you did a wonderful job. /cc @cobyism

**Comment by stefenfriesen** [comment]
Awesome, thanks. Should I submit a pull request or send the file directly?

**Comment by parkr** [comment]
The former! :)
