### ISSUE TITLE
Jekyll t-shirts

### ISSUE THREAD

**Issue by andrewbanchich** [jekyll/brand#15]
I was looking for Jekyll t-shirts to purchase online and couldn't find any. Would I be allowed to make them? At the moment I am just interested in making one or two for myself, but I was thinking I might start a Jekyll-powered site to sell Jekyll shirts.

What kind of permissions do I have for this?

Thanks!

**Comment by parkr** [comment]
Thanks for opening the issue. ([Original request](https://talk.jekyllrb.com/t/jekyll-t-shirts/2573).) 

@andrewbanchich I am not a lawyer so please don't construe this for legal advice. From what I gather, the MIT license is permissive about replication of this branding, but vague in many areas. I proposed in #16 to relicense the content under the [Creative Commons Attribution Share-Alike 4.0 license](http://choosealicense.com/licenses/cc-by-sa-4.0/) which is much clearer about your rights and our rights.

I am personally fine with you making a couple for yourself or your friends, but I wouldn't start selling them until the license changes if I were you. Jekyll was created by one of GitHub's co-founders so I'm not clear on whether it's just Coby or Coby & Tom who retain copyright on this branding.

**Comment by jhvanderschee** [comment]
Some ideas for great T-shirts:

[logo] Jekyll 
simple is simply better

I [heart] Jekyll so much
even this shirt is static

[logo] Jekyll
--watch out! I'm static!

**Comment by parkr** [comment]
@andrewbanchich This content is re-licensed as CC-BY 4.0. You should be good to go on making those t-shirts now, just follow the requests of the license!

**Comment by andrewbanchich** [comment]
@parkr Awesome, thanks! Just to clarify, this means I can now sell shirts as long as I add a link to Jekyll's site on the sales page?

**Comment by parkr** [comment]
@andrewbanchich I'm not a lawyer, but my understanding is: You need to attribute the design to Coby Chapple, state the license, and link to the license in this repo. I found this helpful: https://www.plagiarismtoday.com/2010/01/12/how-to-correctly-use-creative-commons-works/

If you are producing a shirt which allows for a custom tag by the back of the neck, it'd be a good idea to state that the logo used is licensed under CC-BY 4.0. If you can't, then including it on the website is a must :smile:
